### ISSUE TITLE
Transition to rules-and-actions model to acquire extensibility

### ISSUE THREAD

**Issue by oakcask** [oakcask/github-action-auto-label-issue#588]
## Idea

Wants to make configuration file more declarative,  rules-and-actions form.
Here is the current configuration scheme which only allows to add / remove label, with a strange "removeOnMissing" parameter:

```yaml
pirate:caribbean:
  removeOnMissing: true
  all:
    - label: rum
    - any:
      - "[Aa]hoy"
      - "[Mm]atey"
      - ([AR]a*|Ya+)rrr+!
```

Change it to this:

```yaml
---
- id: detect-caribbean-pirate-in-issue
  when: &detect-caribbean-pirate-in-issue
    all:
    - is: issue
    - label: rum
    - any:
      - "[Aa]hoy"
      - "[Mm]atey"
      - ([AR]a*|Ya+)rrr+!
  then:
    - add-label: pirate:caribbean
- id: reverse-detect-caribbean-pirate-in-issue
  when:
    not: *detect-caribbean-pirate-in-issue
  then:
    - remove-label: pirate:caribbean
```

## Future prospects

- setting output for matching rule will help composing complex workflow by labels and contents of issues
